apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-vigo-gateway_rogfk_no
      fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "rogfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta/rogfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/rogfk-no/api/vigo"
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs.instance.gateway"
          value: "DEBUG"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/rogfk-no/actuator/health"
    target:
      kind: Application
      name: fint-flyt-vigo-gateway
