apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-vigo-gateway_afk_no
      fintlabs.no/org-id: afk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/afk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/afk-no/api/vigo"
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs.instance.gateway"
          value: "INFO"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/afk-no/actuator/health"
    target:
      kind: Application
      name: fint-flyt-vigo-gateway

