apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-vigo-gateway
  namespace: novari-no
  labels:
    app.kubernetes.io/name: fint-flyt-vigo-gateway
    app.kubernetes.io/instance: fint-flyt-vigo-gateway_novari_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: novari.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: novari.no
  image: ghcr.io/fintlabs/fint-flyt-vigo-gateway:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  url:
    hostname: flyt.vigoiks.no
    basePath: ""
  ingress:
    enabled: true
    basePath: path
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  envFrom:
    - secretRef:
        name: fint-flyt-file-oauth2-client
  resources:
    limits:
      memory: "2048Mi"
      cpu: "1"
    requests:
      memory: "512Mi"
      cpu: "100m"
  probes:
    readiness:
      path: /actuator/health/readiness
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
    liveness:
      path: /actuator/health/liveness
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
