apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-vigo-gateway_bfk_no
  fintlabs.no/org-id: bfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta/bfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/bfk-no/api/vigo"
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs.instance.gateway"
          value: "DEBUG"
    target:
      kind: Application
      name: fint-flyt-vigo-gateway
