name: CD Deploy

on:
  workflow_run:
    workflows:
      - CI Build
    types:
      - completed

jobs:
  deploy:
    uses: FINTLabs/fint-flyt-github-workflows/.github/workflows/java-app-cd-deploy.yaml@main
    with:
      deploy-targets: |
        [
          {"org":"afk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"afk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"agderfk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"agderfk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"bfk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"bfk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"ffk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"ffk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"innlandetfylke-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"innlandetfylke-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"mrfylke-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"nfk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"ofk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"ofk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"rogfk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"rogfk-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"telemarkfylke-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"telemarkfylke-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"tromsfylke-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"tromsfylke-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"trondelagfylke-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"trondelagfylke-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"vestfoldfylke-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"vestfoldfylke-no","cluster":"aks-api-fint-2022-02-08"},
          {"org":"vlfk-no","cluster":"aks-beta-fint-2021-11-23"},
          {"org":"vlfk-no","cluster":"aks-api-fint-2022-02-08"}
        ]
    secrets: inherit
